(source "gnu" "http://elpa.emacs-china.org/gnu/")
(source "melpa" "http://elpa.emacs-china.org/melpa/")
(source "melpa-stable" "http://elpa.emacs-china.org/melpa-stable/")

(depends-on "alert")
(depends-on "anaconda-mode")
(depends-on "async")
(depends-on "auto-yasnippet")
(depends-on "cask")
(depends-on "company")
(depends-on "company-anaconda")
(depends-on "counsel")
(depends-on "dash")
(depends-on "epl")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-nerd-commenter")
(depends-on "evil-surround")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "gntp")
(depends-on "goto-chg")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-core")
(depends-on "hungry-delete")
(depends-on "iedit")
(depends-on "ivy")
(depends-on "jedi")
(depends-on "log4e")
(depends-on "monokai-theme" :git "https://github.com/oneKelvinSmith/monokai-emacs" :ref "61c0ff7")
(depends-on "monokai-theme")
(depends-on "mwe-log-commands")
(depends-on "org-pomodoro")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "powerline-evil")
(depends-on "pythonic")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smartparens")
(depends-on "swiper")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "which-key")
(depends-on "window-numbering")
(depends-on "yasnippet")
